version: "3"

services:
  app:
    image: aesirxio/bi-app:latest
    pull_policy: always
    environment:
      REACT_APP_ENDPOINT_URL: ${REACT_APP_ENDPOINT_URL}
      REACT_APP_BI_ENDPOINT_URL: ${REACT_APP_BI_ENDPOINT_URL}
      REACT_APP_WEB3_API_ENDPOINT: ${REACT_APP_WEB3_API_ENDPOINT}
      REACT_APP_ENDPOINT_ANALYTICS_URL: ${REACT_APP_ENDPOINT_ANALYTICS_URL}
      REACT_APP_SSO_CLIENT_ID: ${REACT_APP_SSO_CLIENT_ID}
      REACT_APP_SSO_CLIENT_SECRET: ${REACT_APP_SSO_CLIENT_SECRET}
      REACT_APP_SSO_CONCORDIUM_NETWORK: ${REACT_APP_SSO_CONCORDIUM_NETWORK}
      REACT_APP_HEADER_JWT: ${REACT_APP_HEADER_JWT}
      REACT_APP_WOOCOMMERCE_MENU: ${REACT_APP_WOOCOMMERCE_MENU}
      REACT_APP_DATA_STREAM: ${REACT_APP_DATA_STREAM}
      REACT_APP_DEMO_USER: ${REACT_APP_DEMO_USER}
      REACT_APP_DEMO_PASSWORD: ${REACT_APP_DEMO_PASSWORD}
      REACT_APP_LOGIN_EMAIL: ${REACT_APP_LOGIN_EMAIL}
    ports:
      - "${PORT-3000}:3000"
