version: "3"

services:
  app:
    image: aesirxio/bi-app:latest
    pull_policy: always
    environment:
      REACT_APP_BI_ENDPOINT_URL: ${REACT_APP_BI_ENDPOINT_URL}
      REACT_APP_SSO_CLIENT_ID: ${REACT_APP_SSO_CLIENT_ID}
      REACT_APP_SSO_CLIENT_SECRET: ${REACT_APP_SSO_CLIENT_SECRET}
      REACT_APP_HEADER_JWT: ${REACT_APP_HEADER_JWT}
      REACT_APP_DATA_STREAM: ${REACT_APP_DATA_STREAM}
    ports:
      - "${PORT-3000}:3000"
